apiVersion: v1
kind: Secret
metadata:
  name: nodejs-app-secret
  namespace: nodejs-app
type: Opaque

stringData:
  DB_HOST: "database-1.cte22iwae3p4.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_USER: "nodeuser"
  DB_PASSWORD: "YOUR_NEW_PASSWORD"
  DB_NAME: "node_mysql_crud"
